spring.application.name=duan_kthp
server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GraduationManagement;encrypt=true;trustServerCertificate=true;
# Điền username mật khẩu SQL Server của bạn vào đây:
spring.datasource.username=sa
spring.datasource.password=123123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
